[package]
distribution = "2201.13.4"
org= "pesaratest"
name= "ms.teams"
version= "2.3.0"
authors = ["pesaratest"]
keywords = ["Communication/Team Chat", "Cost/Paid", "Vendor/Microsoft", "Area/Communication", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/RisinuWijeisnghe/module-ballerinax-microsoft.teams"
license = ["Apache-2.0"]

[build-options]
observability-included=true

