[package]
org = "ballerinax"
name = "channel_member_management"
version = "0.1.0"
distribution = "2201.13.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "microsoft.teams"
version = "2.3.0"
repository = "local"
